<?php
/**
 * @file
 * Code for the Livre feature.
 */

include_once 'hyx_livre.features.inc';

/**
 * Implements hook_ctools_plugin_directory
 */
function hyx_livre_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * Implement hook_preprocess_node
 */
function hyx_livre_preprocess_node(&$variables) {
    if($variables['node']->type == 'livre') {
        $variables['theme_hook_suggestions'][] = 'node__'.$variables['node']->type.'__'.$variables['view_mode'];
    }
}
