<?php
/**
 * @file
 * Drupal needs this blank file.
 */

function hyx_commerce_commerce_paypal_wps_order_form_data_alter(&$data, $order) {
  $wrapper = entity_metadata_wrapper('commerce_order', $order);
  $products = array();
  foreach ($wrapper->commerce_line_items as $delta => $line_item_wrapper) {
    if($line_item_wrapper->type->value() == 'product') {
      $products[] = htmlentities($line_item_wrapper->commerce_product->title->value(), ENT_QUOTES, "UTF-8");
    }
  }

  $addon = join(', ',$products);
  $data['item_name_1'] = $data['item_name_1'] . ' : ' . $addon;
}